### ISSUE TITLE
Speed of kinematic optimizer

### ISSUE THREAD

**Issue by jionie** [davrempe/contact-human-dynamics#9]
Hi, thanks for the great work! I tried to run the physical mocap part (kinematic optimization + retargeting + physics based optimization),  in paper you mentioned "for a 2 second (60 frame) video clip, the physical optimization usually takes from 30 minutes to 1 hour" and I found kinematic optimization is slow too, should it be very fast? I'm not sure if this is normal or not, looking forward to your response, thanks!!

**Comment by davrempe** [comment]
The kinematic optimization can indeed be slow as well, although usually not as slow as the physics optimization. It often depends on the input motion (e.g. if MTC does poorly or there are complex contact patterns it may take longer). Our implementation is not particularly optimized (we just use scipy) and the settings are geared toward accuracy rather than speed - you might be able to play with the number of iterations and termination conditions to get faster results if desired. Just keep in mind the key goal for the kinematic optimization is to get a motion that will actually be possible to recreate with the physics-based model (esp. wrt foot contacts).
